version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chat
      PORT: 5001
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my_network

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://129.148.23.144:5001 # Comunicação interna
      VITE_CHAT_SERVICE_URL: http://localhost:11434
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my_network

volumes:
  db-data:

networks:
  my_network:
    driver: bridge
